import { Metadata } from "next";
import { getLocale } from "next-intl/server";
import React from "react";

export const metadata: Metadata = {
  title: "starter-kit",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <main className="min-h-[600px] main_main mb-[123px] md:mb-0">
      {children}
    </main>
  );
}
